---
openapi: 3.0.1
info:
  title: Impacto Manager
  description: Sistema de gerenciamento de escola de esportes
  termsOfService: |-
    class License {
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
        identifier: null
    }
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/turma/{id}":
    get:
      tags:
        - Turmas
      summary: Retorna uma turma específica
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Turma"
    put:
      tags:
        - Turmas
      summary: Atualiza os valores de uma turma existente
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Turma"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Turma"
    delete:
      tags:
        - Turmas
      summary: Exclui uma turma existente
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  "/api/professor/{id}":
    get:
      tags:
        - Professor
      summary: Busca um professor específico
      operationId: findById_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Professor"
    put:
      tags:
        - Professor
      summary: Atualiza um professor
      operationId: update_1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Professor"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Professor"
    delete:
      tags:
        - Professor
      summary: Excluir professor
      operationId: delete_1
      parameters:
        - name: id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  "/api/aluno/{id}":
    get:
      tags:
        - Alunos
      summary: Buscar alunos por id
      operationId: findById_2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Aluno"
    put:
      tags:
        - Alunos
      summary: Editar dados
      operationId: update_2
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Aluno"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Aluno"
    delete:
      tags:
        - Alunos
      summary: Exclui aluno
      operationId: delete_2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  "/api/turma":
    get:
      tags:
        - Turmas
      summary: Retorna todas as turmas
      operationId: findAll_1
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Turma"
    post:
      tags:
        - Turmas
      summary: Cria uma nova turma
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Turma"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Turma"
  "/api/professor":
    get:
      tags:
        - Professor
      summary: Busca todos os professores existentes
      operationId: findAll_2
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Professor"
    post:
      tags:
        - Professor
      summary: Adiciona um professor
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Professor"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Professor"
  "/api/aluno":
    get:
      tags:
        - Alunos
      summary: Buscar alunos
      operationId: findAll_5
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Aluno"
    post:
      tags:
        - Alunos
      summary: Novo Aluno
      operationId: create_2
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Aluno"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Aluno"
  "/api/turma/":
    get:
      tags:
        - Turmas
      summary: Retorna todas as turmas
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Turma"
  "/api/professor/":
    get:
      tags:
        - Professor
      summary: Busca todos os professores existentes
      operationId: findAll_3
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Professor"
  "/api/aluno/":
    get:
      tags:
        - Alunos
      summary: Buscar alunos
      operationId: findAll_4
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Aluno"
components:
  schemas:
    Aluno:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        cpf:
          type: string
        sexo:
          type: string
          enum:
            - MASCULINO
            - FEMININO
        dataNascimento:
          type: string
          format: date
        telefone:
          type: string
        cep:
          type: string
        rua:
          type: string
        bairro:
          type: string
        cidade:
          type: string
        numeroCasa:
          type: string
        complemento:
          type: string
        responsavel01:
          type: string
        telefoneResponsavel01:
          type: string
        responsavel02:
          type: string
        telefoneResponsavel02:
          type: string
    Professor:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
    Turma:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        dia01:
          type: string
        dia02:
          type: string
        horario:
          type: string
        alunos:
          type: array
          items:
            "$ref": "#/components/schemas/Aluno"
        professores:
          type: array
          items:
            "$ref": "#/components/schemas/Professor"
