spring:
  web:
    cors:
      allowed:
        origins:
          - http://localhost:4200
          - http://localhost:3000/
          - https://meu-dominio.com
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        headers:
          - Content-Type
          - Authorization