name: SonarQube Analysis for Java 21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarQube scanner
        uses: actions/cache@v2
        id: sonar-cache
        with:
          path: ~/.sonar/cache
          key: $GITHUB_SHA

      - name: Run SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=<your_project_key>
            -Dsonar.sources=.
            -Dsonar.language=java
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.junit.reportsPath=**/target/surefire-reports
            -Dsonar.jacoco.reportPath=**/target/jacoco.exec

      - name: Upload SonarQube report
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: sonar-report.json